using System;
using System.Collections.Generic;
using System.Numerics;

namespace ProjectEuler.Problems
{
    class Problem29
    {
        public void Method()
        {
            Console.WriteLine("How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?");

            HashSet<BigInteger> results = new HashSet<BigInteger>();
            for (int a = 2; a <= 100; a++)
                for (int b = 2; b <= 100; b++)
                    results.Add(BigInteger.Pow(a, b));
            
            Console.WriteLine($"There are {results.Count} distinct solutions");
        }
    }
}
